name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version you want to release to npm/github'
        required: true
        default: '0.0.0'
        type: string

jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Nodejs Env
        run: echo "NODE_VER=`cat .nvmrc`" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VER }}

      - name: Install dependencies
        run: npm ci

      - name: Create Build
        run: npm run build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.SEMANTIC_RELEASE_NPM_TOKEN }}
        # `npm publish` relies on version specified in package.json file
        run: npm publish --tag ${{ inputs.version }}
